import { chromium } from 'playwright';
const BASE = 'http://localhost:8787';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const errors = [];
const DESK = { width: 1366, height: 900 }, MOB = { width: 390, height: 844 };
const SH = 'shots-v3/';
async function as(email, viewport = DESK, lang = 'en') {
  const ctx = await browser.newContext({ viewport, deviceScaleFactor: viewport === MOB ? 2 : 1 });
  await ctx.addInitScript((l) => { try { localStorage.setItem('hc.lang', l); } catch {} }, lang);
  const p = await ctx.newPage();
  p.on('pageerror', (e) => errors.push(email + ' pageerror: ' + e.message));
  p.on('response', async (r) => { if ((r.url().includes('/rest/') || r.url().includes('/auth/')) && r.status() >= 400) console.log('   HTTP', r.status(), r.url().slice(22, 100), (await r.text()).slice(0, 160)); });
  p.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('Failed to load resource')) errors.push(email + ' console: ' + m.text()); });
  await p.goto(BASE + '/');
  await p.fill('input[name=email]', email); await p.fill('input[name=password]', 'Pass1234!');
  await p.click('button[type=submit]');
  await p.waitForSelector('#page .page-head, #page .card', { timeout: 10000 });
  await p.waitForTimeout(400);
  return p;
}
const go = async (p, hash) => { await p.goto(BASE + '/#/profile'); await p.waitForTimeout(250); await p.goto(BASE + '/' + hash);
  await p.waitForSelector('#page .page-head, #page .card, #page .doc, #page .labels', { timeout: 10000 }); await p.waitForTimeout(700); };
const toastText = async (p) => { await p.waitForSelector('.toast', { timeout: 6000 }); return p.locator('.toast').last().innerText(); };
const step = (s) => console.log('▶', s);
const shot = (p, n) => p.screenshot({ path: SH + n + '.png', fullPage: true });
const overflow = (p) => p.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);

step('wizard bills in TZS (USD rates behind it)');
const mgr = await as('admin@hc.test');
await go(mgr, '#/shipments/new');
await mgr.fill('[data-f="sender.name"]', 'Grace Mwita');
await mgr.fill('[data-f="sender.phone"]', '0754 300 400');
await mgr.fill('[data-f="receiver.name"]', 'Peter Mwita');
await mgr.fill('[data-f="receiver.phone"]', '0713 500 600');
await mgr.click('#next');
await mgr.waitForSelector('[data-mode]'); await mgr.click('[data-mode="air"]'); await mgr.click('[data-dest="DAR"]');
await mgr.click('#next');
await mgr.waitForSelector('[data-it="0.description"]');
await mgr.fill('[data-it="0.description"]', 'Phone accessories'); await mgr.fill('[data-it="0.qty"]', '12');
await mgr.click('#next');
await mgr.waitForSelector('[data-f="weight_kg"]'); await mgr.fill('[data-f="weight_kg"]', '10');
await mgr.click('#next');
await mgr.waitForSelector('[data-f="rate"]'); await mgr.fill('[data-f="rate"]', '5');
await mgr.waitForTimeout(200);
console.log('  price step:', (await mgr.locator('.calc').innerText()).replace(/\s+/g, ' '));
await mgr.click('#next');
await mgr.waitForSelector('#add-ch'); await mgr.click('#add-ch');
await mgr.selectOption('[data-ch="0.charge_type"]', 'packing'); await mgr.fill('[data-ch="0.amount"]', '10');
await mgr.selectOption('[data-ch="0.currency"]', 'USD');
await mgr.click('#add-ch');
await mgr.selectOption('[data-ch="1.charge_type"]', 'delivery'); await mgr.fill('[data-ch="1.amount"]', '20000');
await mgr.waitForTimeout(200);
console.log('  charges:', (await mgr.locator('#sum').innerText()).replace(/\s+/g, ' '));
await shot(mgr, '01-charges-currency');
await mgr.click('#next');
await mgr.waitForSelector('[data-cur]');
console.log('  currency step default:', await mgr.locator('.pick.on b').innerText(), '| fx', await mgr.inputValue('[data-f="fx_rate"]'), '| due', await mgr.inputValue('.form input[readonly]'));
await shot(mgr, '02-currency');
await mgr.click('#next');
await mgr.waitForSelector('.callout.ok');
await mgr.click('#next');
await mgr.waitForURL(/#\/shipment\/[0-9a-f-]{36}$/, { timeout: 10000 });
await mgr.waitForSelector('#page h1.mono'); await mgr.waitForTimeout(900);
const sid = mgr.url().split('/').pop();
const ref = await mgr.locator('#page h1.mono').innerText();
console.log('  created', ref, '| KPIs:', (await mgr.locator('.kpi .v').allInnerTexts()).join(' | '));
await shot(mgr, '03-shipment-tzs');

step('one-click status buttons + persistence');
await mgr.click('.sbtn[data-status="packed"]');
console.log('  toast:', await toastText(mgr));
await mgr.waitForTimeout(900);
console.log('  status now:', await mgr.locator('#page .page-head .badge').first().innerText());
await mgr.reload(); await mgr.waitForSelector('#page .page-head .badge'); await mgr.waitForTimeout(800);
console.log('  after refresh:', await mgr.locator('#page .page-head .badge').first().innerText());
console.log('  current button disabled:', await mgr.locator('.sbtn[data-status="packed"]').isDisabled());
await shot(mgr, '04-status-buttons');

step('GRN without dimensions');
const wh = await as('warehouse@hc.test');
await go(wh, `#/shipment/${sid}/grn`);
await wh.fill('#lines tbody tr:first-child [data-k=pieces]', '12');
await wh.fill('#lines tbody tr:first-child [data-k=weight_kg]', '9.5');
await shot(wh, '05-grn-no-dims');
await wh.click('#save');
await wh.waitForSelector('.modal .btn.primary, .modal .btn.danger', { timeout: 5000 }).catch(() => {});
const okb = wh.locator('.modal .btn.primary, .modal .btn.danger').first();
if (await okb.count()) await okb.click();
console.log('  toast:', await toastText(wh).catch(() => 'n/a'));
await wh.waitForTimeout(1200);
await go(wh, `#/doc/grn/${sid}`);
const grnText = await wh.locator('.doc').innerText();
console.log('  GRN prints:', grnText.includes('—') ? '✓ dashes for missing dimensions' : '✗ no dash found');
console.log('  GRN English title:', grnText.split('\n')[0].includes('GOODS RECEIVED') || grnText.includes('GOODS RECEIVED NOTE') ? '✓' : '✗');
await shot(wh, '06-grn-doc');

step('documents: QR + approval');
await go(mgr, `#/shipment/${sid}`);
await mgr.waitForSelector('#docs table', { timeout: 8000 });
const docRows = await mgr.locator('#docs tbody tr').count();
console.log('  documents listed:', docRows);
console.log('  statuses:', (await mgr.locator('#docs .badge').allInnerTexts()).join(', '));
await shot(mgr, '07-documents');
const verifyHref = await mgr.locator('#docs a[target=_blank]').first().getAttribute('href');
console.log('  verify link:', verifyHref.slice(0, 60) + '…');
await mgr.click('#docs [data-approve]');
console.log('  toast:', await toastText(mgr));
await mgr.waitForTimeout(1000);
console.log('  first doc status:', await mgr.locator('#docs .badge').first().innerText());

step('public verification page');
const pub = await browser.newPage();
await pub.goto(verifyHref.replace('http://localhost:8787', BASE));
await pub.waitForTimeout(1600);
const vtext = (await pub.locator('body').innerText()).replace(/\s+/g, ' ');
console.log('  verify page:', vtext.slice(0, 170));
await shot(pub, '08-verify-page');
await pub.goto(`${BASE}/verify.html?d=nonexistenttoken`); await pub.waitForTimeout(1200);
console.log('  bad token:', (await pub.locator('body').innerText()).replace(/\s+/g, ' ').slice(60, 150));

step('edit invalidates the approval');
await go(mgr, `#/shipment/${sid}`);
await mgr.click('[data-act=charge]'); await mgr.waitForSelector('#cf');
await mgr.selectOption('#cf [name=charge_type]', 'storage');
await mgr.fill('#cf [name=unit_price]', '5000');
await mgr.click('#cs'); await toastText(mgr); await mgr.waitForTimeout(1200);
await mgr.waitForSelector('#docs table');
console.log('  invoice status after edit:', await mgr.locator('#docs tbody tr:first-child .badge').innerText());
await pub.goto(verifyHref.replace('http://localhost:8787', BASE)); await pub.waitForTimeout(1500);
const v2 = (await pub.locator('body').innerText()).replace(/\s+/g, ' ');
console.log('  verify page after edit:', v2.includes('Pending approval') ? '✓ pending again' : '✗', v2.includes('out of date') ? '· warns the printed copy is out of date' : '');

step('counter cannot approve');
const counter = await as('counter@hc.test');
await go(counter, `#/shipment/${sid}`);
await counter.waitForSelector('#docs table', { timeout: 8000 });
console.log('  approve buttons for counter:', await counter.locator('#docs [data-approve]').count());

step('documents stay English when the app is in Swahili');
const sw = await as('admin@hc.test', DESK, 'sw');
await go(sw, `#/doc/invoice/${sid}`);
const invText = await sw.locator('.doc').innerText();
console.log('  invoice heading:', invText.split('\n').find((x) => x.includes('INVOICE')) || '—');
console.log('  no Swahili labels:', /ANKARA|Maelezo|JUMLA|Imelipwa|SALIO/.test(invText) ? '✗ found Swahili' : '✓');
console.log('  shows TZS + rate:', /TZS/.test(invText) && /1 USD =/.test(invText) ? '✓' : '✗');
await shot(sw, '09-invoice-english');
await go(sw, `#/doc/receipt/${(await sw.evaluate(async () => { const { from } = await import('./js/api.js'); const { data } = await from('receipts').select('id').limit(1); return data[0]?.id; })) || ''}`).catch(() => {});

step('mobile widths · no horizontal overflow');
const mob = await as('admin@hc.test', MOB, 'sw');
for (const [name, hash] of [['dashboard', '#/'], ['list', '#/shipments'], ['detail', `#/shipment/${sid}`], ['wizard', '#/shipments/new'], ['customers', '#/customers']]) {
  await go(mob, hash);
  const o = await overflow(mob);
  console.log(`  ${name}: overflow ${o}px`, o <= 1 ? '✓' : '✗');
  await shot(mob, `10-m-${name}`);
}
await go(mob, `#/shipment/${sid}`);
await mob.locator('.sbtn').first().scrollIntoViewIfNeeded();
await shot(mob, '11-m-status-buttons');

console.log('\nERRORS:', errors.length ? errors : 'none');
await browser.close();
